MoiveHub/Controllers/ActorController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoiveHub.Data;
using MoiveHub.Data.Services;
using MoiveHub.Data.Statics;
using MoiveHub.Models;
using System.Data;

namespace MoiveHub.Controllers
{

  
    public class ActorController: Controller
    {
        private readonly IActorServices _services;

        public ActorController(IActorServices service)
        {
           _services = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _services.GetAllAsync();
            return View(data);
        }

        //get actors-create
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ActorName,ActorUrl,Bio")]Actor actor)
        {
            if(ModelState.IsValid)
            {
                return View(actor);
            }
            await _services.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }

        //get details by id
        public async Task<IActionResult> Detail(int id)
        {
            var actorDetail = await _services.GetByIdAsync(id);
            if (actorDetail == null)
                return View("Empty");
            return View(actorDetail);
        }

        //get actors-Edit
        public async Task<IActionResult> Edit(int id)
        {

            var actorDetails = await _services.GetByIdAsync(id);
            if (actorDetails ==null) return View("empty");
            return View(actorDetails);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,ActorName,ActorUrl,Bio")] Actor actor)
        {
            if (ModelState.IsValid)
            {
                return View(actor);
            }
            await _services.UpdateAsync(id,actor);
            return RedirectToAction(nameof(Index));
        }
        //Delete
        public async Task<IActionResult> Delete(int id)
        {

            var actorDetails = await _services.GetByIdAsync(id);
            if (actorDetails ==null) return View("NoFound");
            return View(actorDetails);

        }

        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConformation(int id)
        {
            var actorDetails = await _services.GetByIdAsync(id);
            if (actorDetails == null) return View("not found");
          
            await _services.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }

    
}

MoiveHub/Controllers/CinemaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoiveHub.Data;
using MoiveHub.Data.Services;
using MoiveHub.Data.Statics;
using MoiveHub.Models;
using System.Data;

namespace MoiveHub.Controllers
{
    
    public class CinemaController : Controller
    {
        private readonly ICinemaServices _services;

        public CinemaController(ICinemaServices service)
        {
            _services = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _services.GetAllAsync();
            return View(data);
        }
        //get actors-create
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("CinemaName,CinemaUrl,Description")] Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                return View(cinema);
            }
            await _services.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }

        //get details by id
        public async Task<IActionResult> Detail(int id)
        {
            var cinemaDetail = await _services.GetByIdAsync(id);
            if (cinemaDetail == null)
                return View("Empty");
            return View(cinemaDetail);
        }

        //get actors-Edit
        public async Task<IActionResult> Edit(int id)
        {

            var cinemaDetails = await _services.GetByIdAsync(id);
            if (cinemaDetails ==null) return View("empty");
            return View(cinemaDetails);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,CinemaName,CinemaUrl,Description")] Cinema cinema)
        {
            if (ModelState.IsValid)
            {
                return View(cinema);
            }
            await _services.UpdateAsync(id, cinema);
            return RedirectToAction(nameof(Index));
        }
        //Delete
        public async Task<IActionResult> Delete(int id)
        {

            var cinemaDetails = await _services.GetByIdAsync(id);
            if (cinemaDetails ==null) return View("NoFound");
            return View(cinemaDetails);

        }

        [HttpPost , ActionName("Delete")]
        public async Task<IActionResult> DeleteConformation(int id)
        {
            var cinemaDetails = await _services.GetByIdAsync(id);
            if (cinemaDetails == null) return View("not found");

            await _services.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

MoiveHub/Controllers/MovieController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MoiveHub.Data;
using MoiveHub.Data.Services;
using MoiveHub.Data.Statics;
using MoiveHub.Data.ViewModel;
using MoiveHub.Models;

namespace MoiveHub.Controllers
{
   
    public class MovieController : Controller
    {
        private readonly IMovieServices _services;

        public MovieController(IMovieServices service)
        {
            _services = service;
        }

        public async Task<IActionResult> Index()
        {
            var allMovies = await _services.GetAllAsync(n=>n.Cinema);
            return View(allMovies);
        }
        //get actors-create
        public async Task<IActionResult> Create()
        {
            var movieDropDown = await  _services.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropDown.Cinemas, "Id", "CinemaName");
            ViewBag.Producer = new SelectList(movieDropDown.Producers, "Id", "ProducerName");
            ViewBag.Actors = new SelectList(movieDropDown.Actors, "Id", "ActorName");
            return View();
        }
      
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieModel movie)
        {
            if (ModelState.IsValid)
            {
                var movieDropDown = await _services.GetNewMovieDropdownsValues();
                ViewBag.Cinemas = new SelectList(movieDropDown.Cinemas, "Id", "CinemaName");
                ViewBag.Producers = new SelectList(movieDropDown.Producers, "Id", "ProducerName");
                ViewBag.Actors = new SelectList(movieDropDown.Actors, "Id", "ActorName");
                return View(movie);
            }
            await _services.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        //get details by id
      
        public async Task<IActionResult> Detail(int id)
        {
            var movieDetail = await _services.GetMovieByIdAsync(id);
            if (movieDetail == null) return View("Empty");
            return View(movieDetail);
           
        }
        //get actors-Edit
        public async Task<IActionResult> Edit(int id)
        {

            var movieDetails = await _services.GetMovieByIdAsync(id);
            if (movieDetails ==null) return View("empty");
            var response = new NewMovieModel()
            {
                Id = movieDetails.Id,
                MovieName = movieDetails.MovieName,
                Description = movieDetails.Description,
                Prize = movieDetails.Prize,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                MovieUrl = movieDetails.MovieUrl,
                MovieCatogory = movieDetails.MovieCatogory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorId = movieDetails.Actor_Movies.Select(n => n.ActorId).ToList(),
            };
           
            var movieDropDown = await _services.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropDown.Cinemas, "Id", "CinemaName");
            ViewBag.Producer = new SelectList(movieDropDown.Producers, "Id", "ProducerName");
            ViewBag.Actors = new SelectList(movieDropDown.Actors, "Id", "ActorName");
            
            return View(response);

        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieModel movie)
        {
            if (id != movie.Id) return View("NotFound");
            if (!ModelState.IsValid)
            {
                var movieDropDown = await _services.GetNewMovieDropdownsValues();
                ViewBag.Cinemas = new SelectList(movieDropDown.Cinemas, "Id", "CinemaName");
                ViewBag.Producer = new SelectList(movieDropDown.Producers, "Id", "ProducerName");
                ViewBag.Actors = new SelectList(movieDropDown.Actors, "Id", "ActorName");
                return View(movie);
            }
            await _services.UpdateNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }
       
        //Delete
        //public async Task<IActionResult> Delete(int id)
        //{

        //    var movieDetails = await _services.GetByIdAsync(id);
        //    if (movieDetails ==null) return View("NoFound");
        //    return View(movieDetails);

        //}

        //[HttpPost, ActionName("Delete")]
        //public async Task<IActionResult> DeleteConformation(int id)
        //{
        //    var movieDetails = await _services.GetMovieByIdAsync(id);
        //    if (movieDetails == null) return View("not found");

        //    await _services.DeleteAsync(id);
        //    return RedirectToAction(nameof(Index));
        //}
        //Filter movie
        public async Task<IActionResult> Filter(string searchString)
        {
            var allMovie = await _services.GetAllAsync(n=>n.Cinema);

            if (!string.IsNullOrEmpty(searchString))
            {
                //var filteredResult = allMovies.Where(n => n.MovieName.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allMovie.Where(n => string.Equals(n.MovieName, searchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, searchString, StringComparison.CurrentCultureIgnoreCase)).ToList();

                return View("Index", filteredResultNew);
            }

            return View("Index", allMovie);
        }

    }
}

MoiveHub/Controllers/ProducerController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MoiveHub.Data;
using MoiveHub.Data.Services;
using MoiveHub.Data.Statics;
using MoiveHub.Models;
using System.Data;

namespace MoiveHub.Controllers
{
   
    public class ProducerController : Controller
    {
        private readonly IProducerServices _services;

        public ProducerController(IProducerServices service)
        {
            _services = service;
        }

        public async Task<IActionResult> Index()
        {
            var data = await _services.GetAllAsync();
            return View(data);
        }
        //get actors-create
        public IActionResult Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProducerName,ProducerUrl,Bio")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                return View(producer);
            }
            await _services.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }

        //get details by id
        public async Task<IActionResult> Detail(int id)
        {
            var ProducerDetail = await _services.GetByIdAsync(id);
            if (ProducerDetail == null)
                return View("Empty");
            return View(ProducerDetail);
        }

        //get actors-Edit
        public async Task<IActionResult> Edit(int id)
        {

            var ProducerDetail = await _services.GetByIdAsync(id);
            if (ProducerDetail ==null) return View("empty");
            return View(ProducerDetail);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,ProducerName,ProducerUrl,Bio")] Producer producer)
        {
            if (ModelState.IsValid)
            {
                return View(producer);
            }
            await _services.UpdateAsync(id, producer);
            return RedirectToAction(nameof(Index));
        }
        //Delete
        public async Task<IActionResult> Delete(int id)
        {

            var producerDetails = await _services.GetByIdAsync(id);
            if (producerDetails ==null) return View("NoFound");
            return View(producerDetails);

        }

        [HttpPost , ActionName("Delete")]
        public async Task<IActionResult> DeleteConformation(int id)
        {
            var producerDetails = await _services.GetByIdAsync(id);
            if (producerDetails == null) return View("not found");

            await _services.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

MoiveHub/Views/Shared/NotFound.cshtml
<div class="row">
    <div class="col-md-6 offset-3">
        <h1 class="text-info">You've reached the end of the internet</h1>
        <hr />
        <a class="btn btn-outline-success" asp-controller="Movies" asp-action="Index">Home Page</a>
    </div>
</div>

MoiveHub/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MoiveHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MoiveHub.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Movie" asp-action="Index">MoiveHub</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="navbar-nav ">
                            <a class="nav-link text-dark" asp-controller="Movie" asp-action="Index"><i class="badge-info bi-film"></i> Movies</a>
                        </li>
                        
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="bi bi-gear"></i>Management
                                </a>

                                <ul class="dropdown-content" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-controller="Cinema" asp-action="Index"><i class="bi bi-camera-reels"></i>Cinema</a>
                                    <a class="dropdown-item" asp-controller="Producer" asp-action="Index"><i class="bi bi-headset"></i>Producer</a>
                                    <a class="dropdown-item" asp-controller="Actor" asp-action="Index"><i class="bi bi-person-square"></i>Actor</a>
                                </ul>

                            </li>
                        
                        
                    </ul>
                    <form class="form-inline my-2 my-lg-0" asp-controller="Movie" asp-action="Filter" style="padding-right: 25px;">
                        <input name="searchString" type="text" class="form-control" placeholder="Search for a movie.">
                        <button class="btn btn-outline-success" type="submit"><i class="bi bi-search"></i></button>
                    </form>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MoiveHub
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("scripts", required:false)
</body>
</html>
<style>
    /* Example CSS for the dropdown menu */
   

    nav ul li {
        display: inline-block;
        position: relative;
        padding: 10px;
    }

    

    .dropdown-content {
        display: none;
        position: absolute;
        z-index: 1;
    }

    nav ul li:hover .dropdown-content {
        display: block;
    }

    .btn{
        padding : 10px 16px;
    }
</style>